// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFulE_9JLmpFH_XPSV-V-TmX-puP4zza0',
    appId: '1:23676251492:web:7826102c927763c13a9e71',
    messagingSenderId: '23676251492',
    projectId: 'pratikum9-9ae15',
    authDomain: 'pratikum9-9ae15.firebaseapp.com',
    storageBucket: 'pratikum9-9ae15.appspot.com',
    measurementId: 'G-9T29T3VGYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ6MFZZAc426-OdM9e2_is2IYoI0nSsSM',
    appId: '1:23676251492:android:58c53ccbe774470c3a9e71',
    messagingSenderId: '23676251492',
    projectId: 'pratikum9-9ae15',
    storageBucket: 'pratikum9-9ae15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARi7aoU20eTX4nMuhEII8vsbIgN9Ae2vs',
    appId: '1:23676251492:ios:b6ddfc06a6259a773a9e71',
    messagingSenderId: '23676251492',
    projectId: 'pratikum9-9ae15',
    storageBucket: 'pratikum9-9ae15.appspot.com',
    iosBundleId: 'com.example.pratikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARi7aoU20eTX4nMuhEII8vsbIgN9Ae2vs',
    appId: '1:23676251492:ios:b6ddfc06a6259a773a9e71',
    messagingSenderId: '23676251492',
    projectId: 'pratikum9-9ae15',
    storageBucket: 'pratikum9-9ae15.appspot.com',
    iosBundleId: 'com.example.pratikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFulE_9JLmpFH_XPSV-V-TmX-puP4zza0',
    appId: '1:23676251492:web:83184c4caacb0c5d3a9e71',
    messagingSenderId: '23676251492',
    projectId: 'pratikum9-9ae15',
    authDomain: 'pratikum9-9ae15.firebaseapp.com',
    storageBucket: 'pratikum9-9ae15.appspot.com',
    measurementId: 'G-8WQ5BCJW1M',
  );
}
